import json
import ollama

# ─────────────────────────────────────────
# 1. LOAD SIMULATION RESULTS
# ─────────────────────────────────────────

def load_results(path="data/results.json"):
    with open(path, "r") as f:
        return json.load(f)


# ─────────────────────────────────────────
# 2. FORMAT RESULTS FOR THE AI
# ─────────────────────────────────────────

def format_results_for_ai(results):
    """
    Convert the JSON results into a clear
    text summary the AI can understand.
    """

    summary = f"""
SUPPLY CHAIN SIMULATION RESULTS
================================
Disaster        : {results['disaster']} is CLOSED
From            : {results['source']}
To              : {results['target']}
Total Runs      : {results['total_runs']}

SURVIVING ROUTES AFTER DISASTER:
"""

    for route, stats in results['route_summary'].items():
        summary += f"""
  Route       : {route}
  Times Chosen: {stats['times_chosen']} / {results['total_runs']}
  Success Rate: {stats['success_rate']}
  Avg Days    : {stats['avg_days']} days
  Avg Cost    : ${stats['avg_cost']}
"""

    summary += f"""
BEST ROUTE OVERALL:
  {results['best_route']}
  Average {results['best_avg_days']} days | ${results['best_avg_cost']}

NORMAL ROUTE BEFORE DISASTER:
  Through Shanghai_Port
  Average 22 days | $3,200
  (This route is now unavailable)
"""
    return summary


# ─────────────────────────────────────────
# 3. GENERATE THE PLAYBOOK
# ─────────────────────────────────────────

def generate_playbook(model="mistral"):

    print("📂 Loading simulation results...")
    results = load_results()

    print("🧠 Formatting data for AI...")
    simulation_summary = format_results_for_ai(results)

    print(f"🤖 Asking {model} to write the recovery playbook...\n")

    prompt = f"""
You are a supply chain expert. Below are the results of
1000 stress test simulations run on a real supply chain
after a major port closure.

{simulation_summary}

Based on these specific simulation results, write a
PRESCRIPTIVE RECOVERY PLAYBOOK with the following sections:

1. SITUATION SUMMARY
   - What happened and how bad is it

2. IMMEDIATE ACTIONS (Day 1-2)
   - Exact steps to take right now
   - Which specific route to activate and why

3. WHAT TO AVOID
   - Which routes performed worst and why to avoid them

4. COST AND TIME IMPACT
   - How much longer will delivery take
   - How much extra will it cost

5. WHO TO NOTIFY
   - Which stakeholders need to be contacted immediately
   - What to tell them

Be specific. Use the actual route names, days, and costs
from the simulation data above. Do not give generic advice.
"""

    response = ollama.chat(
        model=model,
        messages=[{"role": "user", "content": prompt}]
    )

    playbook = response['message']['content']

    # ── Print the playbook ─────────────────
    print("="*55)
    print("  📋 RECOVERY PLAYBOOK")
    print("="*55)
    print(playbook)

    # ── Save the playbook ──────────────────
    with open("data/playbook.txt", "w", encoding="utf-8") as f:
        f.write("SUPPLY CHAIN RECOVERY PLAYBOOK\n")
        f.write("="*55 + "\n\n")
        f.write(f"Disaster : {results['disaster']}\n")
        f.write(f"Generated by: {model}\n\n")
        f.write("="*55 + "\n\n")
        f.write(playbook)

    print("\n✅ Playbook saved to data/playbook.txt")
    return playbook


# ─────────────────────────────────────────
# 4. RUN IT
# ─────────────────────────────────────────

if __name__ == "__main__":

    # Change "mistral" to "phi3" if using phi3
    generate_playbook(model="mistral")